version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    environment:
      DB_HOST: mysql
    build: .
    container_name: job_board_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/usr/src/app

volumes:
  mysql_data:
